$('.navbar-toggler').click(function () {
    $('.navbar-toggler i').toggleClass('fa-bars fa-times');
});

let carData = [{"car_name":"Volkswagen","model_name":"Phaeton","product_year":2006},
    {"car_name":"Daewoo","model_name":"Nubira","product_year":2000},
    {"car_name":"Porsche","model_name":"Carrera GT","product_year":2005},
    {"car_name":"Mercedes-Benz","model_name":"R-Class","product_year":2006},
    {"car_name":"Acura","model_name":"RL","product_year":1999},
    {"car_name":"Buick","model_name":"Century","product_year":1991},
    {"car_name":"Buick","model_name":"Park Avenue","product_year":1992},
    {"car_name":"Mitsubishi","model_name":"Diamante","product_year":1994},
    {"car_name":"Oldsmobile","model_name":"Cutlass Cruiser","product_year":1993},
    {"car_name":"Dodge","model_name":"Neon","product_year":1996},
    {"car_name":"Lincoln","model_name":"Aviator","product_year":2003},
    {"car_name":"Toyota","model_name":"Tacoma Xtra","product_year":1995},
    {"car_name":"Lexus","model_name":"LX","product_year":2000},
    {"car_name":"Nissan","model_name":"Pathfinder","product_year":2008},
    {"car_name":"Chevrolet","model_name":"Sonic","product_year":2012},
    {"car_name":"Geo","model_name":"Metro","product_year":1996},
    {"car_name":"Subaru","model_name":"Alcyone SVX","product_year":1996},
    {"car_name":"Volkswagen","model_name":"Touareg","product_year":2007},
    {"car_name":"Pontiac","model_name":"Firebird","product_year":2000},
    {"car_name":"Holden","model_name":"VS Commodore","product_year":1995},
    {"car_name":"Mercedes-Benz","model_name":"CL-Class","product_year":2001},
    {"car_name":"Ford","model_name":"Crown Victoria","product_year":1999},
    {"car_name":"Mitsubishi","model_name":"Mirage","product_year":1998},
    {"car_name":"Audi","model_name":"V8","product_year":1990},
    {"car_name":"Chevrolet","model_name":"Express 3500","product_year":2006},
    {"car_name":"Honda","model_name":"Odyssey","product_year":2005},
    {"car_name":"Mazda","model_name":"MX-6","product_year":1994},
    {"car_name":"Porsche","model_name":"911","product_year":1997},
    {"car_name":"GMC","model_name":"Yukon","product_year":1999},
    {"car_name":"Subaru","model_name":"Impreza WRX","product_year":2010},
    {"car_name":"GMC","model_name":"Envoy XL","product_year":2004},
    {"car_name":"Ram","model_name":"2500","product_year":2012},
    {"car_name":"Nissan","model_name":"Murano","product_year":2012},
    {"car_name":"Pontiac","model_name":"Trans Sport","product_year":1998},
    {"car_name":"Jeep","model_name":"Liberty","product_year":2004},
    {"car_name":"Buick","model_name":"Reatta","product_year":1988},
    {"car_name":"Subaru","model_name":"XT","product_year":1986},
    {"car_name":"Dodge","model_name":"Ram Van 2500","product_year":1999},
    {"car_name":"Pontiac","model_name":"Firefly","product_year":1995},
    {"car_name":"Ford","model_name":"F-Series","product_year":1990},
    {"car_name":"Hyundai","model_name":"Sonata","product_year":1999},
    {"car_name":"Pontiac","model_name":"Vibe","product_year":2004},
    {"car_name":"Audi","model_name":"A4","product_year":2012},
    {"car_name":"Mercedes-Benz","model_name":"400SE","product_year":1992},
    {"car_name":"Pontiac","model_name":"Vibe","product_year":2003},
    {"car_name":"GMC","model_name":"Sierra 1500","product_year":2012},
    {"car_name":"Buick","model_name":"Rendezvous","product_year":2003},
    {"car_name":"BMW","model_name":"6 Series","product_year":1989},
    {"car_name":"Mercedes-Benz","model_name":"CL-Class","product_year":2011},
    {"car_name":"Chevrolet","model_name":"Sportvan G20","product_year":1994},
    {"car_name":"GMC","model_name":"Sonoma","product_year":1993},
    {"car_name":"Mitsubishi","model_name":"Montero","product_year":1997},
    {"car_name":"Honda","model_name":"Ridgeline","product_year":2011},
    {"car_name":"BMW","model_name":"X5","product_year":2008},
    {"car_name":"Saturn","model_name":"S-Series","product_year":1994},
    {"car_name":"Dodge","model_name":"Ram 1500 Club","product_year":1999},
    {"car_name":"Jaguar","model_name":"XK","product_year":2008},
    {"car_name":"Mercedes-Benz","model_name":"C-Class","product_year":1994},
    {"car_name":"Mitsubishi","model_name":"Starion","product_year":1988},
    {"car_name":"Infiniti","model_name":"FX","product_year":2010},
    {"car_name":"Infiniti","model_name":"G","product_year":2007},
    {"car_name":"GMC","model_name":"Savana 2500","product_year":2006},
    {"car_name":"Hyundai","model_name":"Tiburon","product_year":2001},
    {"car_name":"Chevrolet","model_name":"Caprice","product_year":1992},
    {"car_name":"Pontiac","model_name":"Firebird","product_year":1969},
    {"car_name":"Porsche","model_name":"Panamera","product_year":2013},
    {"car_name":"Jaguar","model_name":"S-Type","product_year":2003},
    {"car_name":"Cadillac","model_name":"Escalade","product_year":2005},
    {"car_name":"Porsche","model_name":"911","product_year":1991},
    {"car_name":"Acura","model_name":"TSX","product_year":2005},
    {"car_name":"Jaguar","model_name":"XJ","product_year":2011},
    {"car_name":"Mazda","model_name":"Miata MX-5","product_year":2007},
    {"car_name":"Lexus","model_name":"ES","product_year":2009},
    {"car_name":"Buick","model_name":"Regal","product_year":2012},
    {"car_name":"Mercedes-Benz","model_name":"CL-Class","product_year":2003},
    {"car_name":"Ford","model_name":"Taurus","product_year":2006},
    {"car_name":"Isuzu","model_name":"Hombre","product_year":1999},
    {"car_name":"Ford","model_name":"Bronco","product_year":1990},
    {"car_name":"Mitsubishi","model_name":"Lancer","product_year":2009},
    {"car_name":"Hyundai","model_name":"Veloster","product_year":2013},
    {"car_name":"Buick","model_name":"Riviera","product_year":1991},
    {"car_name":"BMW","model_name":"M3","product_year":2005},
    {"car_name":"Ford","model_name":"F450","product_year":2011},
    {"car_name":"Chevrolet","model_name":"Venture","product_year":1998},
    {"car_name":"Ford","model_name":"F150","product_year":1995},
    {"car_name":"Saturn","model_name":"Relay","product_year":2005},
    {"car_name":"Audi","model_name":"90","product_year":1988},
    {"car_name":"GMC","model_name":"Sonoma","product_year":1995},
    {"car_name":"GMC","model_name":"Vandura G3500","product_year":1995},
    {"car_name":"Plymouth","model_name":"Colt Vista","product_year":1992},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":1998},
    {"car_name":"Infiniti","model_name":"I","product_year":2001},
    {"car_name":"Mercedes-Benz","model_name":"E-Class","product_year":2011},
    {"car_name":"Isuzu","model_name":"i-Series","product_year":2006},
    {"car_name":"Mitsubishi","model_name":"Galant","product_year":2011},
    {"car_name":"Dodge","model_name":"Viper","product_year":2008},
    {"car_name":"Ford","model_name":"Aerostar","product_year":1994},
    {"car_name":"Eagle","model_name":"Talon","product_year":1996},
    {"car_name":"Suzuki","model_name":"SJ","product_year":1989},
    {"car_name":"Toyota","model_name":"Camry","product_year":1997},
    {"car_name":"Mitsubishi","model_name":"Starion","product_year":1985},
    {"car_name":"Land Rover","model_name":"Freelander","product_year":2011},
    {"car_name":"Ford","model_name":"Aerostar","product_year":1993},
    {"car_name":"Jaguar","model_name":"XJ Series","product_year":2003},
    {"car_name":"Ford","model_name":"Explorer","product_year":1997},
    {"car_name":"Volkswagen","model_name":"Cabriolet","product_year":1993},
    {"car_name":"Ford","model_name":"Taurus","product_year":2006},
    {"car_name":"Bentley","model_name":"Mulsanne","product_year":2011},
    {"car_name":"Dodge","model_name":"Caravan","product_year":2007},
    {"car_name":"Mitsubishi","model_name":"Chariot","product_year":1990},
    {"car_name":"Ford","model_name":"Econoline E150","product_year":2002},
    {"car_name":"Toyota","model_name":"Tercel","product_year":1992},
    {"car_name":"Lexus","model_name":"ES","product_year":2004},
    {"car_name":"Chevrolet","model_name":"G-Series G20","product_year":1994},
    {"car_name":"Mitsubishi","model_name":"L300","product_year":1989},
    {"car_name":"Acura","model_name":"Integra","product_year":1998},
    {"car_name":"Kia","model_name":"Amanti","product_year":2009},
    {"car_name":"GMC","model_name":"2500 Club Coupe","product_year":1992},
    {"car_name":"Volkswagen","model_name":"Routan","product_year":2009},
    {"car_name":"Mercedes-Benz","model_name":"Sprinter 2500","product_year":2012},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":1987},
    {"car_name":"Ford","model_name":"Bronco","product_year":1993},
    {"car_name":"Cadillac","model_name":"Escalade EXT","product_year":2012},
    {"car_name":"GMC","model_name":"Vandura 3500","product_year":1992},
    {"car_name":"Pontiac","model_name":"Sunfire","product_year":2004},
    {"car_name":"GMC","model_name":"Suburban 1500","product_year":1999},
    {"car_name":"Mitsubishi","model_name":"Eclipse","product_year":1990},
    {"car_name":"Nissan","model_name":"Quest","product_year":2005},
    {"car_name":"Ford","model_name":"Contour","product_year":1998},
    {"car_name":"Pontiac","model_name":"Bonneville","product_year":1996},
    {"car_name":"Hyundai","model_name":"XG350","product_year":2005},
    {"car_name":"GMC","model_name":"3500 Club Coupe","product_year":1997},
    {"car_name":"Lincoln","model_name":"Mark VII","product_year":1984},
    {"car_name":"GMC","model_name":"3500","product_year":1992},
    {"car_name":"GMC","model_name":"Sierra 2500","product_year":2009},
    {"car_name":"Dodge","model_name":"Ram 1500","product_year":2001},
    {"car_name":"Ram","model_name":"3500","product_year":2011},
    {"car_name":"Volvo","model_name":"V70","product_year":2007},
    {"car_name":"Honda","model_name":"Pilot","product_year":2004},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":1983},
    {"car_name":"Dodge","model_name":"Grand Caravan","product_year":1996},
    {"car_name":"Toyota","model_name":"T100 Xtra","product_year":1998},
    {"car_name":"Toyota","model_name":"Corolla","product_year":2011},
    {"car_name":"Pontiac","model_name":"Trans Sport","product_year":1999},
    {"car_name":"Honda","model_name":"Pilot","product_year":2010},
    {"car_name":"Toyota","model_name":"Corolla","product_year":2006},
    {"car_name":"Mercury","model_name":"Mountaineer","product_year":1998},
    {"car_name":"Nissan","model_name":"Altima","product_year":2012},
    {"car_name":"Subaru","model_name":"Impreza","product_year":2001},
    {"car_name":"Mazda","model_name":"Mazda3","product_year":2009},
    {"car_name":"Suzuki","model_name":"SX4","product_year":2011},
    {"car_name":"Land Rover","model_name":"Discovery","product_year":2001},
    {"car_name":"Mitsubishi","model_name":"Starion","product_year":1986},
    {"car_name":"Acura","model_name":"TL","product_year":2001},
    {"car_name":"Kia","model_name":"Sorento","product_year":2003},
    {"car_name":"Suzuki","model_name":"SJ","product_year":1985},
    {"car_name":"Dodge","model_name":"Ram 50","product_year":1993},
    {"car_name":"Chrysler","model_name":"Fifth Ave","product_year":1992},
    {"car_name":"Ford","model_name":"Econoline E150","product_year":2000},
    {"car_name":"Suzuki","model_name":"Samurai","product_year":1994},
    {"car_name":"Subaru","model_name":"Outback","product_year":2000},
    {"car_name":"Plymouth","model_name":"Grand Voyager","product_year":1997},
    {"car_name":"Mercedes-Benz","model_name":"E-Class","product_year":1990},
    {"car_name":"Mitsubishi","model_name":"Galant","product_year":2009},
    {"car_name":"Chevrolet","model_name":"Silverado 3500","product_year":2012},
    {"car_name":"Honda","model_name":"Pilot","product_year":2008},
    {"car_name":"Saab","model_name":"9-3","product_year":2007},
    {"car_name":"GMC","model_name":"Acadia","product_year":2012},
    {"car_name":"Pontiac","model_name":"Tempest","product_year":1961},
    {"car_name":"Honda","model_name":"Civic GX","product_year":2003},
    {"car_name":"Chevrolet","model_name":"Tahoe","product_year":2010},
    {"car_name":"Nissan","model_name":"Titan","product_year":2008},
    {"car_name":"GMC","model_name":"Savana 3500","product_year":2002},
    {"car_name":"Ford","model_name":"E-Series","product_year":1963},
    {"car_name":"Nissan","model_name":"Murano","product_year":2007},
    {"car_name":"Chevrolet","model_name":"G-Series 2500","product_year":1996},
    {"car_name":"Volkswagen","model_name":"New Beetle","product_year":2006},
    {"car_name":"Ferrari","model_name":"430 Scuderia","product_year":2008},
    {"car_name":"Hummer","model_name":"H2","product_year":2006},
    {"car_name":"Dodge","model_name":"Ram 3500","product_year":1995},
    {"car_name":"GMC","model_name":"Yukon XL 1500","product_year":2002},
    {"car_name":"Ford","model_name":"Thunderbird","product_year":2004},
    {"car_name":"Smart","model_name":"Fortwo","product_year":2009},
    {"car_name":"Mitsubishi","model_name":"Eclipse","product_year":2004},
    {"car_name":"Chevrolet","model_name":"Express 2500","product_year":2012},
    {"car_name":"Oldsmobile","model_name":"Silhouette","product_year":2001},
    {"car_name":"BMW","model_name":"Z3","product_year":1997},
    {"car_name":"Mercury","model_name":"Mountaineer","product_year":2007},
    {"car_name":"Cadillac","model_name":"Escalade","product_year":1999},
    {"car_name":"Mazda","model_name":"Miata MX-5","product_year":2006},
    {"car_name":"Ford","model_name":"Tempo","product_year":1994},
    {"car_name":"Pontiac","model_name":"Montana","product_year":2005},
    {"car_name":"Volkswagen","model_name":"Passat","product_year":2008},
    {"car_name":"Daewoo","model_name":"Nubira","product_year":2000},
    {"car_name":"Porsche","model_name":"911","product_year":1990},
    {"car_name":"Mitsubishi","model_name":"Galant","product_year":2005},
    {"car_name":"GMC","model_name":"Savana","product_year":2008},
    {"car_name":"Land Rover","model_name":"Discovery Series II","product_year":2001},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":2008},
    {"car_name":"Mazda","model_name":"Familia","product_year":1991},
    {"car_name":"Ford","model_name":"Escort ZX2","product_year":2003},
    {"car_name":"BMW","model_name":"Z4 M","product_year":2008},
    {"car_name":"Dodge","model_name":"Avenger","product_year":1999},
    {"car_name":"Honda","model_name":"Civic","product_year":1980},
    {"car_name":"Mitsubishi","model_name":"Lancer Evolution","product_year":2006},
    {"car_name":"Buick","model_name":"Reatta","product_year":1990},
    {"car_name":"Nissan","model_name":"Rogue","product_year":2010},
    {"car_name":"Lincoln","model_name":"Mark VIII","product_year":1995},
    {"car_name":"Lexus","model_name":"LX","product_year":2006},
    {"car_name":"Lincoln","model_name":"Town Car","product_year":1984},
    {"car_name":"Ford","model_name":"Freestyle","product_year":2007},
    {"car_name":"Nissan","model_name":"Titan","product_year":2009},
    {"car_name":"Honda","model_name":"Pilot","product_year":2002},
    {"car_name":"Ford","model_name":"E-Series","product_year":2006},
    {"car_name":"Cadillac","model_name":"CTS-V","product_year":2011},
    {"car_name":"Aston Martin","model_name":"V8 Vantage","product_year":2010},
    {"car_name":"Chevrolet","model_name":"Camaro","product_year":1976},
    {"car_name":"Subaru","model_name":"Alcyone SVX","product_year":1997},
    {"car_name":"Land Rover","model_name":"LR2","product_year":2012},
    {"car_name":"Jeep","model_name":"Liberty","product_year":2005},
    {"car_name":"Ford","model_name":"Aerostar","product_year":1986},
    {"car_name":"Oldsmobile","model_name":"Alero","product_year":2000},
    {"car_name":"Honda","model_name":"Prelude","product_year":1994},
    {"car_name":"Lincoln","model_name":"MKS","product_year":2010},
    {"car_name":"GMC","model_name":"Savana 3500","product_year":2003},
    {"car_name":"Mitsubishi","model_name":"Chariot","product_year":1992},
    {"car_name":"Saab","model_name":"900","product_year":1996},
    {"car_name":"Chevrolet","model_name":"Cobalt","product_year":2010},
    {"car_name":"Buick","model_name":"Coachbuilder","product_year":1990},
    {"car_name":"Honda","model_name":"Civic","product_year":2000},
    {"car_name":"Mercury","model_name":"Mountaineer","product_year":2006},
    {"car_name":"Lexus","model_name":"CT","product_year":2011},
    {"car_name":"Volvo","model_name":"XC90","product_year":2010},
    {"car_name":"Mercury","model_name":"Mountaineer","product_year":2008},
    {"car_name":"Mercedes-Benz","model_name":"Sprinter","product_year":2010},
    {"car_name":"Ford","model_name":"F-Series","product_year":2005},
    {"car_name":"Chrysler","model_name":"300M","product_year":2003},
    {"car_name":"Toyota","model_name":"4Runner","product_year":2005},
    {"car_name":"Mazda","model_name":"CX-9","product_year":2009},
    {"car_name":"Toyota","model_name":"MR2","product_year":1995},
    {"car_name":"Mazda","model_name":"GLC","product_year":1984},
    {"car_name":"Honda","model_name":"Element","product_year":2009},
    {"car_name":"Suzuki","model_name":"Sidekick","product_year":1996},
    {"car_name":"Audi","model_name":"Q5","product_year":2009},
    {"car_name":"Plymouth","model_name":"Neon","product_year":2000},
    {"car_name":"Buick","model_name":"Riviera","product_year":1993},
    {"car_name":"Subaru","model_name":"Forester","product_year":1999},
    {"car_name":"Chevrolet","model_name":"S10 Blazer","product_year":1994},
    {"car_name":"Toyota","model_name":"4Runner","product_year":1996},
    {"car_name":"Toyota","model_name":"Land Cruiser","product_year":2007},
    {"car_name":"Hyundai","model_name":"Tucson","product_year":2007},
    {"car_name":"Ford","model_name":"GT500","product_year":2007},
    {"car_name":"Honda","model_name":"Fit","product_year":2008},
    {"car_name":"Subaru","model_name":"Impreza WRX","product_year":2010},
    {"car_name":"Chevrolet","model_name":"Corvette","product_year":1962},
    {"car_name":"Ford","model_name":"Mustang","product_year":1969},
    {"car_name":"Hyundai","model_name":"Accent","product_year":2008},
    {"car_name":"Infiniti","model_name":"QX56","product_year":2010},
    {"car_name":"Chevrolet","model_name":"S10","product_year":1993},
    {"car_name":"Spyker","model_name":"C8","product_year":2005},
    {"car_name":"Buick","model_name":"Century","product_year":2003},
    {"car_name":"Land Rover","model_name":"LR3","product_year":2006},
    {"car_name":"Chevrolet","model_name":"Impala","product_year":2011},
    {"car_name":"Dodge","model_name":"Ram 1500","product_year":2006},
    {"car_name":"Chevrolet","model_name":"Corvette","product_year":2005},
    {"car_name":"Mercedes-Benz","model_name":"SLK55 AMG","product_year":2009},
    {"car_name":"Mercedes-Benz","model_name":"W201","product_year":1991},
    {"car_name":"Lamborghini","model_name":"Gallardo","product_year":2007},
    {"car_name":"Mitsubishi","model_name":"Pajero","product_year":1987},
    {"car_name":"MINI","model_name":"Cooper Countryman","product_year":2011},
    {"car_name":"Chevrolet","model_name":"Silverado 1500","product_year":2000},
    {"car_name":"Tesla","model_name":"Roadster","product_year":2010},
    {"car_name":"Lincoln","model_name":"Navigator","product_year":1999},
    {"car_name":"GMC","model_name":"Sierra 3500","product_year":2001},
    {"car_name":"Daewoo","model_name":"Nubira","product_year":1999},
    {"car_name":"Acura","model_name":"CL","product_year":1998},
    {"car_name":"Mitsubishi","model_name":"GTO","product_year":1991},
    {"car_name":"Mitsubishi","model_name":"Starion","product_year":1984},
    {"car_name":"Buick","model_name":"Roadmaster","product_year":1995},
    {"car_name":"Ford","model_name":"Bronco II","product_year":1990},
    {"car_name":"Kia","model_name":"Spectra","product_year":2006},
    {"car_name":"Isuzu","model_name":"Ascender","product_year":2005},
    {"car_name":"Cadillac","model_name":"Fleetwood","product_year":1994},
    {"car_name":"Mercedes-Benz","model_name":"S-Class","product_year":1987},
    {"car_name":"Acura","model_name":"MDX","product_year":2010},
    {"car_name":"Volvo","model_name":"740","product_year":1992},
    {"car_name":"Nissan","model_name":"Frontier","product_year":2009},
    {"car_name":"GMC","model_name":"Sierra 1500","product_year":2012},
    {"car_name":"Chevrolet","model_name":"Suburban 1500","product_year":1992},
    {"car_name":"Volvo","model_name":"S40","product_year":2004},
    {"car_name":"Ford","model_name":"Mustang","product_year":1993},
    {"car_name":"Geo","model_name":"Tracker","product_year":1992},
    {"car_name":"Dodge","model_name":"Stratus","product_year":2005},
    {"car_name":"Volvo","model_name":"S80","product_year":2006},
    {"car_name":"Ford","model_name":"Escort","product_year":1993},
    {"car_name":"Mazda","model_name":"CX-9","product_year":2011},
    {"car_name":"Lamborghini","model_name":"Countach","product_year":1990},
    {"car_name":"Land Rover","model_name":"Defender 90","product_year":1995},
    {"car_name":"Plymouth","model_name":"Laser","product_year":1990},
    {"car_name":"Geo","model_name":"Metro","product_year":1995},
    {"car_name":"GMC","model_name":"Sierra Hybrid","product_year":2006},
    {"car_name":"Lexus","model_name":"LX","product_year":1997},
    {"car_name":"Audi","model_name":"S4","product_year":2011},
    {"car_name":"Lexus","model_name":"LX","product_year":1998},
    {"car_name":"Buick","model_name":"Century","product_year":1985},
    {"car_name":"Buick","model_name":"Skylark","product_year":1996},
    {"car_name":"GMC","model_name":"Suburban 2500","product_year":1999},
    {"car_name":"Ford","model_name":"Expedition","product_year":1999},
    {"car_name":"Lexus","model_name":"IS","product_year":2004},
    {"car_name":"Subaru","model_name":"Alcyone SVX","product_year":1993},
    {"car_name":"GMC","model_name":"1500","product_year":1995},
    {"car_name":"Mercury","model_name":"Sable","product_year":1998},
    {"car_name":"Lexus","model_name":"ES","product_year":1999},
    {"car_name":"Acura","model_name":"RSX","product_year":2002},
    {"car_name":"Hyundai","model_name":"Santa Fe","product_year":2011},
    {"car_name":"Ford","model_name":"Escape","product_year":2008},
    {"car_name":"Dodge","model_name":"Intrepid","product_year":2001},
    {"car_name":"Ford","model_name":"Mustang","product_year":2002},
    {"car_name":"Hyundai","model_name":"Elantra","product_year":2004},
    {"car_name":"Lexus","model_name":"LX","product_year":1996},
    {"car_name":"Cadillac","model_name":"Escalade EXT","product_year":2012},
    {"car_name":"Mazda","model_name":"RX-7","product_year":1987},
    {"car_name":"Pontiac","model_name":"Grand Am","product_year":1994},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":1969},
    {"car_name":"Ford","model_name":"Aspire","product_year":1994},
    {"car_name":"Dodge","model_name":"Ram Van 2500","product_year":2001},
    {"car_name":"Lincoln","model_name":"LS","product_year":2000},
    {"car_name":"Aston Martin","model_name":"DB9","product_year":2010},
    {"car_name":"Ford","model_name":"Bronco","product_year":1994},
    {"car_name":"Lexus","model_name":"GS","product_year":1996},
    {"car_name":"Ford","model_name":"F-Series Super Duty","product_year":2012},
    {"car_name":"Isuzu","model_name":"Ascender","product_year":2003},
    {"car_name":"Porsche","model_name":"911","product_year":1994},
    {"car_name":"Dodge","model_name":"Ram","product_year":2010},
    {"car_name":"GMC","model_name":"Yukon XL 2500","product_year":2012},
    {"car_name":"Dodge","model_name":"Challenger","product_year":2010},
    {"car_name":"Nissan","model_name":"Titan","product_year":2011},
    {"car_name":"Volkswagen","model_name":"Scirocco","product_year":1987},
    {"car_name":"Mitsubishi","model_name":"Mighty Max","product_year":1995},
    {"car_name":"Honda","model_name":"Civic","product_year":1995},
    {"car_name":"Nissan","model_name":"Titan","product_year":2011},
    {"car_name":"Infiniti","model_name":"M","product_year":2011},
    {"car_name":"Buick","model_name":"Riviera","product_year":1979},
    {"car_name":"Suzuki","model_name":"Grand Vitara","product_year":2010},
    {"car_name":"Ford","model_name":"Econoline E250","product_year":1993},
    {"car_name":"Oldsmobile","model_name":"Achieva","product_year":1998},
    {"car_name":"Nissan","model_name":"Versa","product_year":2012},
    {"car_name":"BMW","model_name":"M5","product_year":2000},
    {"car_name":"Nissan","model_name":"Xterra","product_year":2003},
    {"car_name":"Lincoln","model_name":"Aviator","product_year":2004},
    {"car_name":"Ford","model_name":"Bronco","product_year":1988},
    {"car_name":"Chevrolet","model_name":"Malibu Maxx","product_year":2006},
    {"car_name":"Nissan","model_name":"Xterra","product_year":2007},
    {"car_name":"BMW","model_name":"7 Series","product_year":2007},
    {"car_name":"Mercury","model_name":"Mariner","product_year":2008},
    {"car_name":"Dodge","model_name":"Ram 3500","product_year":2008},
    {"car_name":"Nissan","model_name":"Frontier","product_year":2002},
    {"car_name":"Chevrolet","model_name":"Suburban 1500","product_year":2012},
    {"car_name":"Subaru","model_name":"Legacy","product_year":1999},
    {"car_name":"Chevrolet","model_name":"Express 1500","product_year":2004},
    {"car_name":"Mercedes-Benz","model_name":"W201","product_year":1985},
    {"car_name":"GMC","model_name":"Yukon XL 1500","product_year":2008},
    {"car_name":"Ford","model_name":"GT500","product_year":2008},
    {"car_name":"Chevrolet","model_name":"Monte Carlo","product_year":1997},
    {"car_name":"Volkswagen","model_name":"Cabriolet","product_year":1999},
    {"car_name":"Dodge","model_name":"Ram","product_year":2009},
    {"car_name":"Bentley","model_name":"Arnage","product_year":2007},
    {"car_name":"Lexus","model_name":"SC","product_year":1996},
    {"car_name":"Chevrolet","model_name":"Malibu","product_year":2003},
    {"car_name":"Nissan","model_name":"Pathfinder","product_year":1999},
    {"car_name":"Kia","model_name":"Optima","product_year":2003},
    {"car_name":"Ford","model_name":"E350","product_year":2007},
    {"car_name":"Suzuki","model_name":"Forenza","product_year":2007},
    {"car_name":"Pontiac","model_name":"LeMans","product_year":1967},
    {"car_name":"MINI","model_name":"Cooper","product_year":2004},
    {"car_name":"Lexus","model_name":"LX","product_year":1997},
    {"car_name":"Mitsubishi","model_name":"Mighty Max","product_year":1995},
    {"car_name":"Dodge","model_name":"Ram 1500 Club","product_year":1999},
    {"car_name":"Mercury","model_name":"Grand Marquis","product_year":1993},
    {"car_name":"Acura","model_name":"Integra","product_year":1993},
    {"car_name":"BMW","model_name":"X3","product_year":2006},
    {"car_name":"Mercedes-Benz","model_name":"SL-Class","product_year":1998},
    {"car_name":"Mitsubishi","model_name":"Lancer Evolution","product_year":2003},
    {"car_name":"Mazda","model_name":"Tribute","product_year":2011},
    {"car_name":"BMW","model_name":"3 Series","product_year":1997},
    {"car_name":"Acura","model_name":"TL","product_year":2007},
    {"car_name":"Chevrolet","model_name":"Cobalt","product_year":2006},
    {"car_name":"Porsche","model_name":"911","product_year":2000},
    {"car_name":"Lotus","model_name":"Esprit","product_year":1991},
    {"car_name":"Honda","model_name":"Pilot","product_year":2005},
    {"car_name":"Infiniti","model_name":"Q","product_year":2004},
    {"car_name":"Hyundai","model_name":"Elantra","product_year":2013},
    {"car_name":"Audi","model_name":"TT","product_year":2008},
    {"car_name":"Pontiac","model_name":"Bonneville","product_year":1984},
    {"car_name":"Chevrolet","model_name":"Sportvan G30","product_year":1993},
    {"car_name":"Dodge","model_name":"Caravan","product_year":1994},
    {"car_name":"Aston Martin","model_name":"V12 Vantage","product_year":2012},
    {"car_name":"Hyundai","model_name":"Genesis","product_year":2011},
    {"car_name":"Pontiac","model_name":"Sunbird","product_year":1991},
    {"car_name":"Ford","model_name":"Ranger","product_year":2010},
    {"car_name":"Infiniti","model_name":"M","product_year":2010},
    {"car_name":"Ford","model_name":"F250","product_year":1999},
    {"car_name":"Saturn","model_name":"VUE","product_year":2004},
    {"car_name":"Plymouth","model_name":"Roadrunner","product_year":1969},
    {"car_name":"GMC","model_name":"Yukon XL 2500","product_year":2002},
    {"car_name":"Jaguar","model_name":"XF","product_year":2012},
    {"car_name":"Cadillac","model_name":"Escalade","product_year":2000},
    {"car_name":"GMC","model_name":"3500 Club Coupe","product_year":1997},
    {"car_name":"Chevrolet","model_name":"Camaro","product_year":1999},
    {"car_name":"Toyota","model_name":"RAV4","product_year":2002},
    {"car_name":"Hyundai","model_name":"Tucson","product_year":2007},
    {"car_name":"Cadillac","model_name":"STS-V","product_year":2008},
    {"car_name":"Audi","model_name":"Cabriolet","product_year":1994},
    {"car_name":"Mercedes-Benz","model_name":"CL-Class","product_year":2009},
    {"car_name":"Buick","model_name":"Enclave","product_year":2010},
    {"car_name":"Nissan","model_name":"Versa","product_year":2011},
    {"car_name":"GMC","model_name":"Yukon XL 1500","product_year":2000},
    {"car_name":"Lincoln","model_name":"Navigator","product_year":2009},
    {"car_name":"Ford","model_name":"Econoline E150","product_year":1994},
    {"car_name":"BMW","model_name":"745","product_year":2005},
    {"car_name":"Suzuki","model_name":"Esteem","product_year":2000},
    {"car_name":"Lamborghini","model_name":"Diablo","product_year":2000},
    {"car_name":"Bentley","model_name":"Continental","product_year":2006},
    {"car_name":"Saab","model_name":"9-7X","product_year":2007},
    {"car_name":"Ford","model_name":"Mustang","product_year":1989},
    {"car_name":"Audi","model_name":"RS 4","product_year":2007},
    {"car_name":"Suzuki","model_name":"XL-7","product_year":2005},
    {"car_name":"Mitsubishi","model_name":"Pajero","product_year":1991},
    {"car_name":"Maserati","model_name":"Coupe","product_year":2006},
    {"car_name":"Cadillac","model_name":"CTS-V","product_year":2010},
    {"car_name":"GMC","model_name":"Envoy","product_year":2003},
    {"car_name":"GMC","model_name":"1500","product_year":1992},
    {"car_name":"Chevrolet","model_name":"Express 3500","product_year":1997},
    {"car_name":"Chevrolet","model_name":"Lumina","product_year":2001},
    {"car_name":"Ford","model_name":"Ranger","product_year":2002},
    {"car_name":"Ford","model_name":"Mustang","product_year":2010},
    {"car_name":"Mercury","model_name":"Mariner","product_year":2009},
    {"car_name":"Ford","model_name":"F-350 Super Duty","product_year":2006},
    {"car_name":"Geo","model_name":"Storm","product_year":1992},
    {"car_name":"Dodge","model_name":"Caliber","product_year":2009},
    {"car_name":"Saab","model_name":"9-7X","product_year":2007},
    {"car_name":"Kia","model_name":"Rondo","product_year":2008},
    {"car_name":"Nissan","model_name":"350Z","product_year":2006},
    {"car_name":"Honda","model_name":"Element","product_year":2007},
    {"car_name":"Toyota","model_name":"Matrix","product_year":2009},
    {"car_name":"Lamborghini","model_name":"Murciélago","product_year":2008},
    {"car_name":"Honda","model_name":"Prelude","product_year":2000},
    {"car_name":"Honda","model_name":"CR-X","product_year":1985},
    {"car_name":"Lincoln","model_name":"Town Car","product_year":1999},
    {"car_name":"Dodge","model_name":"Ram Van B150","product_year":1994},
    {"car_name":"Buick","model_name":"Reatta","product_year":1990},
    {"car_name":"Lincoln","model_name":"Town Car","product_year":2005},
    {"car_name":"Volkswagen","model_name":"Cabriolet","product_year":1997},
    {"car_name":"Ford","model_name":"Expedition","product_year":2003},
    {"car_name":"Geo","model_name":"Prizm","product_year":1996},
    {"car_name":"Pontiac","model_name":"6000","product_year":1985},
    {"car_name":"Chevrolet","model_name":"Express 3500","product_year":2000},
    {"car_name":"Bentley","model_name":"Arnage","product_year":2006},
    {"car_name":"Mercedes-Benz","model_name":"SL-Class","product_year":1996},
    {"car_name":"Pontiac","model_name":"Bonneville","product_year":1998},
    {"car_name":"Ford","model_name":"Econoline E350","product_year":1994},
    {"car_name":"Honda","model_name":"CR-V","product_year":2007},
    {"car_name":"Suzuki","model_name":"Vitara","product_year":2001},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":2004},
    {"car_name":"Jaguar","model_name":"XJ Series","product_year":1995},
    {"car_name":"Volkswagen","model_name":"Jetta","product_year":1999},
    {"car_name":"Infiniti","model_name":"M","product_year":2004},
    {"car_name":"Audi","model_name":"4000CS Quattro","product_year":1987},
    {"car_name":"Lexus","model_name":"ES","product_year":1999},
    {"car_name":"Infiniti","model_name":"M","product_year":2009},
    {"car_name":"Chevrolet","model_name":"Camaro","product_year":2001},
    {"car_name":"Chevrolet","model_name":"Uplander","product_year":2006},
    {"car_name":"Chevrolet","model_name":"Corvette","product_year":1994},
    {"car_name":"Dodge","model_name":"Ram Wagon B150","product_year":1993},
    {"car_name":"Infiniti","model_name":"I","product_year":2000},
    {"car_name":"Pontiac","model_name":"Sunbird","product_year":1994},
    {"car_name":"Kia","model_name":"Carens","product_year":2008},
    {"car_name":"Subaru","model_name":"Leone","product_year":1987},
    {"car_name":"Mitsubishi","model_name":"Mighty Max Macro","product_year":1993},
    {"car_name":"Chevrolet","model_name":"APV","product_year":1992},
    {"car_name":"Volkswagen","model_name":"Jetta","product_year":1999},
    {"car_name":"Infiniti","model_name":"FX","product_year":2003},
    {"car_name":"Volvo","model_name":"S60","product_year":2006},
    {"car_name":"Mercedes-Benz","model_name":"M-Class","product_year":2012},
    {"car_name":"Buick","model_name":"Verano","product_year":2012},
    {"car_name":"Dodge","model_name":"Ram 3500","product_year":2009},
    {"car_name":"Dodge","model_name":"Magnum","product_year":2008},
    {"car_name":"Acura","model_name":"TL","product_year":2012},
    {"car_name":"Ford","model_name":"Explorer","product_year":1995},
    {"car_name":"Subaru","model_name":"Alcyone SVX","product_year":1996},
    {"car_name":"Nissan","model_name":"Sentra","product_year":1996},
    {"car_name":"Audi","model_name":"A6","product_year":2007},
    {"car_name":"GMC","model_name":"Vandura G1500","product_year":1995},
    {"car_name":"Toyota","model_name":"Matrix","product_year":2008},
    {"car_name":"Buick","model_name":"Regal","product_year":1989},
    {"car_name":"Porsche","model_name":"Cayenne","product_year":2012},
    {"car_name":"Mitsubishi","model_name":"Diamante","product_year":2001},
    {"car_name":"Eagle","model_name":"Talon","product_year":1992},
    {"car_name":"Lotus","model_name":"Exige","product_year":2011},
    {"car_name":"Volvo","model_name":"C70","product_year":2009},
    {"car_name":"Mercury","model_name":"Milan","product_year":2007},
    {"car_name":"Jeep","model_name":"Wrangler","product_year":2000},
    {"car_name":"Toyota","model_name":"Land Cruiser","product_year":2010},
    {"car_name":"GMC","model_name":"Savana 2500","product_year":2001},
    {"car_name":"Audi","model_name":"S4","product_year":2004},
    {"car_name":"Ford","model_name":"Mustang","product_year":1995},
    {"car_name":"Toyota","model_name":"TundraMax","product_year":2009},
    {"car_name":"Chevrolet","model_name":"Lumina","product_year":1993},
    {"car_name":"Ford","model_name":"Expedition","product_year":2005},
    {"car_name":"Isuzu","model_name":"Rodeo","product_year":2004},
    {"car_name":"Chrysler","model_name":"200","product_year":2012},
    {"car_name":"GMC","model_name":"Suburban 1500","product_year":1999},
    {"car_name":"Kia","model_name":"Sephia","product_year":1997},
    {"car_name":"GMC","model_name":"2500","product_year":1996},
    {"car_name":"Nissan","model_name":"Quest","product_year":2011},
    {"car_name":"Oldsmobile","model_name":"Alero","product_year":2000},
    {"car_name":"Mazda","model_name":"RX-7","product_year":1986},
    {"car_name":"Hyundai","model_name":"Accent","product_year":2002},
    {"car_name":"Nissan","model_name":"Maxima","product_year":2005},
    {"car_name":"Suzuki","model_name":"SJ 410","product_year":1984},
    {"car_name":"Mercedes-Benz","model_name":"SLK-Class","product_year":2000},
    {"car_name":"Ford","model_name":"Edge","product_year":2012},
    {"car_name":"Hyundai","model_name":"Excel","product_year":1993},
    {"car_name":"Oldsmobile","model_name":"Cutlass","product_year":1999},
    {"car_name":"Volvo","model_name":"S70","product_year":1999},
    {"car_name":"Dodge","model_name":"Ram Van 1500","product_year":1997},
    {"car_name":"Saab","model_name":"9000","product_year":1997},
    {"car_name":"Porsche","model_name":"944","product_year":1988},
    {"car_name":"Pontiac","model_name":"G6","product_year":2006},
    {"car_name":"Lincoln","model_name":"Mark LT","product_year":2006},
    {"car_name":"Cadillac","model_name":"Fleetwood","product_year":1993},
    {"car_name":"Lexus","model_name":"LX","product_year":2000},
    {"car_name":"Toyota","model_name":"Yaris","product_year":2009},
    {"car_name":"Nissan","model_name":"Armada","product_year":2011},
    {"car_name":"Mercedes-Benz","model_name":"E-Class","product_year":1984},
    {"car_name":"Chevrolet","model_name":"Corvette","product_year":1959},
    {"car_name":"MINI","model_name":"Clubman","product_year":2010},
    {"car_name":"Mercury","model_name":"Marauder","product_year":2003},
    {"car_name":"Nissan","model_name":"NX","product_year":1993},
    {"car_name":"Volvo","model_name":"V40","product_year":2001},
    {"car_name":"Jaguar","model_name":"X-Type","product_year":2007},
    {"car_name":"Ford","model_name":"GT500","product_year":2007},
    {"car_name":"Chevrolet","model_name":"Impala","product_year":2008},
    {"car_name":"Suzuki","model_name":"SX4","product_year":2012},
    {"car_name":"Mazda","model_name":"Familia","product_year":1992},
    {"car_name":"Chrysler","model_name":"Town & Country","product_year":1999},
    {"car_name":"Audi","model_name":"A3","product_year":2011},
    {"car_name":"Toyota","model_name":"Tacoma","product_year":2011},
    {"car_name":"Acura","model_name":"Integra","product_year":1994},
    {"car_name":"MINI","model_name":"Clubman","product_year":2010},
    {"car_name":"Buick","model_name":"Skylark","product_year":1994},
    {"car_name":"Pontiac","model_name":"6000","product_year":1987},
    {"car_name":"Toyota","model_name":"Corolla","product_year":1995},
    {"car_name":"Chevrolet","model_name":"Avalanche 1500","product_year":2005},
    {"car_name":"Dodge","model_name":"Neon","product_year":1998},
    {"car_name":"Ford","model_name":"E-Series","product_year":1988},
    {"car_name":"Audi","model_name":"S6","product_year":2010},
    {"car_name":"Toyota","model_name":"Matrix","product_year":2009},
    {"car_name":"Dodge","model_name":"Ram 1500","product_year":2001},
    {"car_name":"Ford","model_name":"Probe","product_year":1990},
    {"car_name":"GMC","model_name":"Suburban 1500","product_year":1994},
    {"car_name":"Hyundai","model_name":"Elantra","product_year":2006},
    {"car_name":"Honda","model_name":"CR-V","product_year":2003},
    {"car_name":"Lincoln","model_name":"Mark VIII","product_year":1998},
    {"car_name":"Ford","model_name":"Tempo","product_year":1989},
    {"car_name":"Ford","model_name":"F-Series","product_year":2003},
    {"car_name":"Chevrolet","model_name":"Cobalt","product_year":2005},
    {"car_name":"Lexus","model_name":"ES","product_year":2009},
    {"car_name":"Chevrolet","model_name":"Tahoe","product_year":1996},
    {"car_name":"Volvo","model_name":"C70","product_year":2009},
    {"car_name":"Ford","model_name":"Windstar","product_year":2003},
    {"car_name":"Dodge","model_name":"Dakota","product_year":2002},
    {"car_name":"Volvo","model_name":"960","product_year":1995},
    {"car_name":"Lotus","model_name":"Esprit","product_year":1998},
    {"car_name":"Chevrolet","model_name":"Tracker","product_year":2002},
    {"car_name":"Volvo","model_name":"XC70","product_year":2011},
    {"car_name":"GMC","model_name":"Savana 1500","product_year":1999},
    {"car_name":"Volvo","model_name":"960","product_year":1995},
    {"car_name":"Mazda","model_name":"MX-5","product_year":1995},
    {"car_name":"Lotus","model_name":"Esprit","product_year":1987},
    {"car_name":"GMC","model_name":"Sierra 2500","product_year":1999},
    {"car_name":"GMC","model_name":"Yukon XL 2500","product_year":2007},
    {"car_name":"Infiniti","model_name":"Q","product_year":1993},
    {"car_name":"Mazda","model_name":"Miata MX-5","product_year":1996},
    {"car_name":"Lexus","model_name":"RX","product_year":2011},
    {"car_name":"Nissan","model_name":"Leaf","product_year":2011},
    {"car_name":"Hyundai","model_name":"Sonata","product_year":2005},
    {"car_name":"Toyota","model_name":"Tundra","product_year":2003},
    {"car_name":"Mercury","model_name":"Tracer","product_year":1995},
    {"car_name":"Dodge","model_name":"Viper","product_year":1997},
    {"car_name":"Acura","model_name":"Legend","product_year":1988},
    {"car_name":"GMC","model_name":"Suburban 1500","product_year":1993},
    {"car_name":"GMC","model_name":"Sierra 2500","product_year":2003},
    {"car_name":"Ford","model_name":"Courier","product_year":1986},
    {"car_name":"Audi","model_name":"Allroad","product_year":2004},
    {"car_name":"Toyota","model_name":"TundraMax","product_year":2010},
    {"car_name":"Eagle","model_name":"Summit","product_year":1996},
    {"car_name":"Lexus","model_name":"ES","product_year":1992},
    {"car_name":"GMC","model_name":"Safari","product_year":2002},
    {"car_name":"Chrysler","model_name":"LeBaron","product_year":1994},
    {"car_name":"Dodge","model_name":"Intrepid","product_year":1993},
    {"car_name":"Mazda","model_name":"RX-7","product_year":1984},
    {"car_name":"BMW","model_name":"Z4 M","product_year":2009},
    {"car_name":"Hyundai","model_name":"Sonata","product_year":2007},
    {"car_name":"GMC","model_name":"2500 Club Coupe","product_year":1995},
    {"car_name":"Mazda","model_name":"MX-3","product_year":1995},
    {"car_name":"Mercury","model_name":"Mountaineer","product_year":2005},
    {"car_name":"Chevrolet","model_name":"G-Series 2500","product_year":1997},
    {"car_name":"GMC","model_name":"Yukon","product_year":2013},
    {"car_name":"Lamborghini","model_name":"Diablo","product_year":2000},
    {"car_name":"Ford","model_name":"Fusion","product_year":2013},
    {"car_name":"Chevrolet","model_name":"Classic","product_year":2004},
    {"car_name":"Mitsubishi","model_name":"Galant","product_year":2002},
    {"car_name":"Lexus","model_name":"CT","product_year":2011},
    {"car_name":"Toyota","model_name":"Camry","product_year":2009},
    {"car_name":"Lincoln","model_name":"MKX","product_year":2012},
    {"car_name":"Ford","model_name":"Crown Victoria","product_year":1996},
    {"car_name":"Cadillac","model_name":"Fleetwood","product_year":1996},
    {"car_name":"Suzuki","model_name":"XL-7","product_year":2008},
    {"car_name":"Volkswagen","model_name":"CC","product_year":2013},
    {"car_name":"Mercedes-Benz","model_name":"M-Class","product_year":2008},
    {"car_name":"Buick","model_name":"Riviera","product_year":1993},
    {"car_name":"Infiniti","model_name":"FX","product_year":2008},
    {"car_name":"Cadillac","model_name":"Eldorado","product_year":1999},
    {"car_name":"Ford","model_name":"F-Series Super Duty","product_year":2008},
    {"car_name":"Maybach","model_name":"Landaulet","product_year":2010},
    {"car_name":"Lexus","model_name":"RX","product_year":2008},
    {"car_name":"Jaguar","model_name":"X-Type","product_year":2002},
    {"car_name":"Mazda","model_name":"Miata MX-5","product_year":1995},
    {"car_name":"Chevrolet","model_name":"Express 3500","product_year":2002},
    {"car_name":"Ford","model_name":"Club Wagon","product_year":1994},
    {"car_name":"Cadillac","model_name":"XLR","product_year":2007},
    {"car_name":"Saturn","model_name":"S-Series","product_year":1993},
    {"car_name":"Toyota","model_name":"TundraMax","product_year":2007},
    {"car_name":"Toyota","model_name":"Tacoma","product_year":2002},
    {"car_name":"Ford","model_name":"Tempo","product_year":1988},
    {"car_name":"Audi","model_name":"Coupe Quattro","product_year":1991},
    {"car_name":"Porsche","model_name":"928","product_year":1989},
    {"car_name":"Ford","model_name":"Fusion","product_year":2010},
    {"car_name":"Mitsubishi","model_name":"Outlander","product_year":2004},
    {"car_name":"Ford","model_name":"Escort ZX2","product_year":2003},
    {"car_name":"Pontiac","model_name":"Bonneville","product_year":1986},
    {"car_name":"Chrysler","model_name":"PT Cruiser","product_year":2002},
    {"car_name":"Chevrolet","model_name":"Suburban 2500","product_year":2001},
    {"car_name":"Toyota","model_name":"Matrix","product_year":2012},
    {"car_name":"Alfa Romeo","model_name":"Spider","product_year":1994},
    {"car_name":"Lincoln","model_name":"Continental","product_year":1998},
    {"car_name":"Mercury","model_name":"Milan","product_year":2008},
    {"car_name":"Dodge","model_name":"D150","product_year":1993},
    {"car_name":"Mercedes-Benz","model_name":"E-Class","product_year":2007},
    {"car_name":"Dodge","model_name":"Charger","product_year":2010},
    {"car_name":"Mercedes-Benz","model_name":"S-Class","product_year":2008},
    {"car_name":"Mazda","model_name":"Miata MX-5","product_year":2006},
    {"car_name":"Ford","model_name":"Contour","product_year":1996},
    {"car_name":"Oldsmobile","model_name":"98","product_year":1994},
    {"car_name":"Kia","model_name":"Rondo","product_year":2008},
    {"car_name":"Jeep","model_name":"Wrangler","product_year":2003},
    {"car_name":"Mitsubishi","model_name":"GTO","product_year":1990},
    {"car_name":"Volkswagen","model_name":"New Beetle","product_year":2002},
    {"car_name":"Land Rover","model_name":"Freelander","product_year":2009},
    {"car_name":"Mitsubishi","model_name":"Galant","product_year":1987},
    {"car_name":"Nissan","model_name":"Sentra","product_year":2012},
    {"car_name":"Ford","model_name":"Explorer","product_year":2011},
    {"car_name":"Chrysler","model_name":"LeBaron","product_year":1994},
    {"car_name":"Hyundai","model_name":"XG350","product_year":2004},
    {"car_name":"Lotus","model_name":"Exige","product_year":2004},
    {"car_name":"Honda","model_name":"Fit","product_year":2011},
    {"car_name":"Mazda","model_name":"Tribute","product_year":2010},
    {"car_name":"GMC","model_name":"Yukon XL 2500","product_year":2003},
    {"car_name":"GMC","model_name":"Savana 1500","product_year":2009},
    {"car_name":"Chevrolet","model_name":"APV","product_year":1993},
    {"car_name":"Chevrolet","model_name":"Camaro","product_year":2012},
    {"car_name":"Suzuki","model_name":"Aerio","product_year":2006},
    {"car_name":"Mercedes-Benz","model_name":"Sprinter","product_year":2011},
    {"car_name":"Ford","model_name":"Crown Victoria","product_year":1996},
    {"car_name":"Cadillac","model_name":"Eldorado","product_year":2000},
    {"car_name":"Chevrolet","model_name":"TrailBlazer","product_year":2006},
    {"car_name":"Buick","model_name":"Regal","product_year":1996},
    {"car_name":"Ford","model_name":"Expedition","product_year":1998},
    {"car_name":"Toyota","model_name":"Previa","product_year":1996},
    {"car_name":"Cadillac","model_name":"SRX","product_year":2005},
    {"car_name":"Ford","model_name":"Mustang","product_year":2010},
    {"car_name":"Chevrolet","model_name":"Tracker","product_year":2003},
    {"car_name":"Dodge","model_name":"Nitro","product_year":2010},
    {"car_name":"Mercury","model_name":"Tracer","product_year":1991},
    {"car_name":"Volkswagen","model_name":"GTI","product_year":2011},
    {"car_name":"Buick","model_name":"Century","product_year":1988},
    {"car_name":"Buick","model_name":"Electra","product_year":1986},
    {"car_name":"Chevrolet","model_name":"Monza","product_year":1975},
    {"car_name":"GMC","model_name":"Sierra 3500","product_year":2009},
    {"car_name":"Ford","model_name":"F250","product_year":2000},
    {"car_name":"Saab","model_name":"900","product_year":1984},
    {"car_name":"Isuzu","model_name":"Trooper","product_year":1997},
    {"car_name":"Rolls-Royce","model_name":"Phantom","product_year":2009},
    {"car_name":"Mazda","model_name":"RX-7","product_year":1994},
    {"car_name":"Porsche","model_name":"911","product_year":2005},
    {"car_name":"Lincoln","model_name":"Continental Mark VII","product_year":1991},
    {"car_name":"Mercedes-Benz","model_name":"GL-Class","product_year":2007},
    {"car_name":"Volvo","model_name":"960","product_year":1997},
    {"car_name":"Buick","model_name":"LeSabre","product_year":1987},
    {"car_name":"Buick","model_name":"Riviera","product_year":1996},
    {"car_name":"Aston Martin","model_name":"DB9","product_year":2008},
    {"car_name":"Geo","model_name":"Prizm","product_year":1993},
    {"car_name":"Daewoo","model_name":"Leganza","product_year":1999},
    {"car_name":"BMW","model_name":"M5","product_year":2001},
    {"car_name":"Nissan","model_name":"Sentra","product_year":1995},
    {"car_name":"Mercedes-Benz","model_name":"CL-Class","product_year":2008},
    {"car_name":"Buick","model_name":"Regal","product_year":2012},
    {"car_name":"Honda","model_name":"Civic","product_year":2004},
    {"car_name":"Dodge","model_name":"Viper","product_year":2005},
    {"car_name":"Mazda","model_name":"929","product_year":1994},
    {"car_name":"Dodge","model_name":"Dakota Club","product_year":2001},
    {"car_name":"Infiniti","model_name":"Q","product_year":1999},
    {"car_name":"Mazda","model_name":"B-Series","product_year":1986},
    {"car_name":"Pontiac","model_name":"Grand Am","product_year":1999},
    {"car_name":"Mercedes-Benz","model_name":"CL-Class","product_year":2007},
    {"car_name":"Mitsubishi","model_name":"Truck","product_year":1996},
    {"car_name":"Lincoln","model_name":"Blackwood","product_year":2003},
    {"car_name":"Toyota","model_name":"Tacoma","product_year":2000},
    {"car_name":"Chevrolet","model_name":"Silverado 2500","product_year":2003},
    {"car_name":"Land Rover","model_name":"Defender","product_year":1995},
    {"car_name":"Acura","model_name":"TL","product_year":2003},
    {"car_name":"Mazda","model_name":"Mazda3","product_year":2008},
    {"car_name":"Cadillac","model_name":"Eldorado","product_year":1999},
    {"car_name":"Maserati","model_name":"Quattroporte","product_year":2010},
    {"car_name":"Chrysler","model_name":"Voyager","product_year":2002},
    {"car_name":"Dodge","model_name":"Caravan","product_year":2011},
    {"car_name":"Volkswagen","model_name":"Golf","product_year":1996},
    {"car_name":"Chevrolet","model_name":"Suburban 2500","product_year":2002},
    {"car_name":"Lincoln","model_name":"Town Car","product_year":1986},
    {"car_name":"Kia","model_name":"Sportage","product_year":2009},
    {"car_name":"Audi","model_name":"200","product_year":1991},
    {"car_name":"Porsche","model_name":"911","product_year":1999},
    {"car_name":"Ford","model_name":"F250","product_year":2000},
    {"car_name":"Porsche","model_name":"928","product_year":1991},
    {"car_name":"Lexus","model_name":"LS","product_year":1998},
    {"car_name":"Infiniti","model_name":"QX56","product_year":2009},
    {"car_name":"Saab","model_name":"9-2X","product_year":2006},
    {"car_name":"Nissan","model_name":"Sentra","product_year":2008},
    {"car_name":"Oldsmobile","model_name":"Aurora","product_year":1997},
    {"car_name":"Land Rover","model_name":"Discovery","product_year":1999},
    {"car_name":"Mercedes-Benz","model_name":"R-Class","product_year":2008},
    {"car_name":"Chevrolet","model_name":"Suburban 2500","product_year":1994},
    {"car_name":"Mercedes-Benz","model_name":"E-Class","product_year":2005},
    {"car_name":"Porsche","model_name":"Cayman","product_year":2010},
    {"car_name":"Pontiac","model_name":"Bonneville","product_year":1986},
    {"car_name":"Suzuki","model_name":"Grand Vitara","product_year":2007},
    {"car_name":"Infiniti","model_name":"G37","product_year":2011},
    {"car_name":"Buick","model_name":"Skylark","product_year":1985},
    {"car_name":"Ford","model_name":"Econoline E150","product_year":1998},
    {"car_name":"Audi","model_name":"Q7","product_year":2009},
    {"car_name":"Cadillac","model_name":"STS-V","product_year":2006},
    {"car_name":"BMW","model_name":"7 Series","product_year":2003},
    {"car_name":"Chevrolet","model_name":"Suburban 2500","product_year":2005},
    {"car_name":"Saturn","model_name":"S-Series","product_year":1996},
    {"car_name":"Aston Martin","model_name":"V8 Vantage","product_year":2009},
    {"car_name":"Mercury","model_name":"Mystique","product_year":1998},
    {"car_name":"Volkswagen","model_name":"Jetta","product_year":1990},
    {"car_name":"MG","model_name":"MGB","product_year":1977},
    {"car_name":"Dodge","model_name":"Ram Van 1500","product_year":1999},
    {"car_name":"Lexus","model_name":"LS","product_year":2008},
    {"car_name":"Volkswagen","model_name":"Jetta","product_year":1985},
    {"car_name":"Plymouth","model_name":"Voyager","product_year":1993},
    {"car_name":"Dodge","model_name":"Ram Van B350","product_year":1993},
    {"car_name":"Saab","model_name":"900","product_year":1985},
    {"car_name":"Mercury","model_name":"Tracer","product_year":1988},
    {"car_name":"Chevrolet","model_name":"2500","product_year":1996},
    {"car_name":"Toyota","model_name":"Avalon","product_year":2004},
    {"car_name":"Ford","model_name":"Expedition","product_year":2008},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":1993},
    {"car_name":"Dodge","model_name":"Dakota Club","product_year":2006},
    {"car_name":"Ford","model_name":"Mustang","product_year":1986},
    {"car_name":"Ford","model_name":"Club Wagon","product_year":1997},
    {"car_name":"Acura","model_name":"Legend","product_year":1994},
    {"car_name":"Bentley","model_name":"Continental Flying Spur","product_year":2011},
    {"car_name":"Mercedes-Benz","model_name":"G-Class","product_year":2003},
    {"car_name":"Maserati","model_name":"Biturbo","product_year":1986},
    {"car_name":"Ford","model_name":"E250","product_year":2009},
    {"car_name":"Aston Martin","model_name":"Vantage","product_year":2007},
    {"car_name":"Hyundai","model_name":"Tiburon","product_year":1997},
    {"car_name":"Kia","model_name":"Sportage","product_year":2000},
    {"car_name":"Saab","model_name":"9-5","product_year":2006},
    {"car_name":"Subaru","model_name":"Alcyone SVX","product_year":1996},
    {"car_name":"Mercedes-Benz","model_name":"CLK-Class","product_year":2002},
    {"car_name":"Porsche","model_name":"911","product_year":2010},
    {"car_name":"Jeep","model_name":"Grand Cherokee","product_year":2004},
    {"car_name":"Nissan","model_name":"Pathfinder","product_year":1993},
    {"car_name":"Volkswagen","model_name":"Passat","product_year":2010},
    {"car_name":"Dodge","model_name":"Viper","product_year":2006},
    {"car_name":"Dodge","model_name":"Dakota","product_year":1999},
    {"car_name":"Chevrolet","model_name":"1500","product_year":1997},
    {"car_name":"Toyota","model_name":"Camry","product_year":1996},
    {"car_name":"Audi","model_name":"riolet","product_year":1995},
    {"car_name":"Toyota","model_name":"Land Cruiser","product_year":1999},
    {"car_name":"Chevrolet","model_name":"Caprice","product_year":1995},
    {"car_name":"Dodge","model_name":"Grand Caravan","product_year":2010},
    {"car_name":"Nissan","model_name":"Frontier","product_year":2010},
    {"car_name":"Porsche","model_name":"Carrera GT","product_year":2004},
    {"car_name":"Mercury","model_name":"Mariner","product_year":2008},
    {"car_name":"Hummer","model_name":"H1","product_year":2004},
    {"car_name":"Cadillac","model_name":"Escalade EXT","product_year":2009},
    {"car_name":"Pontiac","model_name":"Tempest","product_year":1967},
    {"car_name":"Mazda","model_name":"Familia","product_year":1992},
    {"car_name":"Subaru","model_name":"BRZ","product_year":2013},
    {"car_name":"Dodge","model_name":"Ram 2500","product_year":1995},
    {"car_name":"Subaru","model_name":"SVX","product_year":1992},
    {"car_name":"Pontiac","model_name":"Solstice","product_year":2009},
    {"car_name":"Mercedes-Benz","model_name":"C-Class","product_year":1998},
    {"car_name":"BMW","model_name":"5 Series","product_year":1994},
    {"car_name":"Kia","model_name":"Forte","product_year":2012},
    {"car_name":"Subaru","model_name":"SVX","product_year":1996},
    {"car_name":"GMC","model_name":"Sierra 3500","product_year":2000},
    {"car_name":"Maybach","model_name":"57","product_year":2005},
    {"car_name":"Pontiac","model_name":"Grand Prix","product_year":1972},
    {"car_name":"Nissan","model_name":"Xterra","product_year":2005},
    {"car_name":"Land Rover","model_name":"LR3","product_year":2009},
    {"car_name":"Volvo","model_name":"XC90","product_year":2004},
    {"car_name":"Dodge","model_name":"Ram 1500","product_year":2007},
    {"car_name":"Ford","model_name":"Ranger","product_year":2008},
    {"car_name":"Chevrolet","model_name":"S10","product_year":2003},
    {"car_name":"Hyundai","model_name":"Accent","product_year":2013},
    {"car_name":"Mitsubishi","model_name":"Pajero","product_year":2002},
    {"car_name":"Toyota","model_name":"RAV4","product_year":2002},
    {"car_name":"Toyota","model_name":"Land Cruiser","product_year":2011},
    {"car_name":"Toyota","model_name":"Camry","product_year":1995},
    {"car_name":"Acura","model_name":"RL","product_year":2004},
    {"car_name":"Chevrolet","model_name":"S10 Blazer","product_year":1994},
    {"car_name":"Dodge","model_name":"Ram 2500","product_year":2001},
    {"car_name":"Volkswagen","model_name":"Golf","product_year":1986},
    {"car_name":"Nissan","model_name":"Pathfinder","product_year":2001},
    {"car_name":"Scion","model_name":"xD","product_year":2009},
    {"car_name":"Nissan","model_name":"Xterra","product_year":2004},
    {"car_name":"Audi","model_name":"S6","product_year":2002},
    {"car_name":"Daewoo","model_name":"Leganza","product_year":2000},
    {"car_name":"GMC","model_name":"Vandura 3500","product_year":1992},
    {"car_name":"Audi","model_name":"5000S","product_year":1984},
    {"car_name":"BMW","model_name":"525","product_year":2001},
    {"car_name":"Lexus","model_name":"LS","product_year":2001},
    {"car_name":"Mitsubishi","model_name":"Pajero","product_year":2003},
    {"car_name":"Buick","model_name":"Park Avenue","product_year":2003},
    {"car_name":"Mercedes-Benz","model_name":"SL-Class","product_year":2001},
    {"car_name":"Mitsubishi","model_name":"Pajero","product_year":2004},
    {"car_name":"Mazda","model_name":"Mazdaspeed 3","product_year":2012},
    {"car_name":"Buick","model_name":"Riviera","product_year":1979},
    {"car_name":"Mercury","model_name":"Grand Marquis","product_year":1985},
    {"car_name":"Pontiac","model_name":"GTO","product_year":1964},
    {"car_name":"Lotus","model_name":"Exige","product_year":2005},
    {"car_name":"Honda","model_name":"CR-V","product_year":2004},
    {"car_name":"Mercury","model_name":"Grand Marquis","product_year":1987},
    {"car_name":"Toyota","model_name":"Prius Plug-in Hybrid","product_year":2012},
    {"car_name":"GMC","model_name":"Vandura 3500","product_year":1993},
    {"car_name":"GMC","model_name":"Sonoma Club Coupe","product_year":1998},
    {"car_name":"Bentley","model_name":"Continental","product_year":2010},
    {"car_name":"Mercedes-Benz","model_name":"W126","product_year":1981},
    {"car_name":"GMC","model_name":"Jimmy","product_year":1997},
    {"car_name":"Chevrolet","model_name":"Uplander","product_year":2005},
    {"car_name":"Mercury","model_name":"Monterey","product_year":2007},
    {"car_name":"Audi","model_name":"RS 4","product_year":2007},
    {"car_name":"Mitsubishi","model_name":"Endeavor","product_year":2007},
    {"car_name":"Buick","model_name":"Regal","product_year":2001},
    {"car_name":"Mercury","model_name":"Grand Marquis","product_year":1991},
    {"car_name":"Kia","model_name":"Optima","product_year":2011},
    {"car_name":"Mercedes-Benz","model_name":"CLS-Class","product_year":2008},
    {"car_name":"GMC","model_name":"Yukon XL 1500","product_year":2005},
    {"car_name":"Dodge","model_name":"Omni","product_year":1978},
    {"car_name":"Mercedes-Benz","model_name":"300SE","product_year":1992},
    {"car_name":"MINI","model_name":"Cooper Clubman","product_year":2012},
    {"car_name":"Ford","model_name":"Transit Connect","product_year":2011},
    {"car_name":"Dodge","model_name":"Dakota","product_year":2001},
    {"car_name":"Dodge","model_name":"Ram 3500","product_year":2009},
    {"car_name":"BMW","model_name":"M6","product_year":2006},
    {"car_name":"Lincoln","model_name":"Mark LT","product_year":2008},
    {"car_name":"Mercury","model_name":"Grand Marquis","product_year":2002},
    {"car_name":"Chevrolet","model_name":"SSR","product_year":2004},
    {"car_name":"Acura","model_name":"Integra","product_year":1988},
    {"car_name":"Lotus","model_name":"Esprit","product_year":1986},
    {"car_name":"Ford","model_name":"F250","product_year":2003},
    {"car_name":"Hyundai","model_name":"Accent","product_year":2010},
    {"car_name":"Acura","model_name":"TL","product_year":2005},
    {"car_name":"Chevrolet","model_name":"Malibu","product_year":2013},
    {"car_name":"Ford","model_name":"F-Series","product_year":2005},
    {"car_name":"Volkswagen","model_name":"R32","product_year":2004},
    {"car_name":"Volkswagen","model_name":"Passat","product_year":2009},
    {"car_name":"Mitsubishi","model_name":"Eclipse","product_year":1994},
    {"car_name":"Mitsubishi","model_name":"Pajero","product_year":1999},
    {"car_name":"Buick","model_name":"Park Avenue","product_year":1999},
    {"car_name":"GMC","model_name":"Safari","product_year":1993},
    {"car_name":"Hyundai","model_name":"HED-5","product_year":2012},
    {"car_name":"Toyota","model_name":"Camry","product_year":2005},
    {"car_name":"Volvo","model_name":"XC70","product_year":2003},
    {"car_name":"Mazda","model_name":"Mazdaspeed6","product_year":2007},
    {"car_name":"Mazda","model_name":"MX-5","product_year":2012},
    {"car_name":"Honda","model_name":"Accord","product_year":2008},
    {"car_name":"Buick","model_name":"Somerset","product_year":1985},
    {"car_name":"Volkswagen","model_name":"GTI","product_year":2007},
    {"car_name":"Kia","model_name":"Sephia","product_year":1995},
    {"car_name":"Jaguar","model_name":"XJ","product_year":2010},
    {"car_name":"Lotus","model_name":"Elan","product_year":1994},
    {"car_name":"Aston Martin","model_name":"Rapide","product_year":2011},
    {"car_name":"Jeep","model_name":"Compass","product_year":2007},
    {"car_name":"Mitsubishi","model_name":"Chariot","product_year":1986},
    {"car_name":"Hyundai","model_name":"Sonata","product_year":2009},
    {"car_name":"Hyundai","model_name":"Santa Fe","product_year":2001},
    {"car_name":"Mitsubishi","model_name":"Mirage","product_year":1997},
    {"car_name":"Chrysler","model_name":"Sebring","product_year":2002},
    {"car_name":"Mitsubishi","model_name":"Starion","product_year":1989},
    {"car_name":"Mitsubishi","model_name":"Mirage","product_year":1991},
    {"car_name":"Pontiac","model_name":"G6","product_year":2010},
    {"car_name":"Volvo","model_name":"XC90","product_year":2011},
    {"car_name":"Acura","model_name":"MDX","product_year":2008},
    {"car_name":"Porsche","model_name":"928","product_year":1988},
    {"car_name":"Scion","model_name":"tC","product_year":2006},
    {"car_name":"Honda","model_name":"Prelude","product_year":2000},
    {"car_name":"Cadillac","model_name":"DeVille","product_year":1997},
    {"car_name":"GMC","model_name":"Sierra Denali","product_year":2006},
    {"car_name":"Chevrolet","model_name":"Suburban 1500","product_year":2011},
    {"car_name":"Subaru","model_name":"Forester","product_year":2008},
    {"car_name":"Mazda","model_name":"Protege","product_year":2000},
    {"car_name":"Volkswagen","model_name":"riolet","product_year":1992},
    {"car_name":"Ford","model_name":"LTD","product_year":1984},
    {"car_name":"Volvo","model_name":"S70","product_year":1999},
    {"car_name":"Hyundai","model_name":"Accent","product_year":1999},
    {"car_name":"Maserati","model_name":"Biturbo","product_year":1985},
    {"car_name":"Acura","model_name":"TL","product_year":1997},
    {"car_name":"Mazda","model_name":"CX-7","product_year":2011},
    {"car_name":"Dodge","model_name":"Ram","product_year":2010},
    {"car_name":"Pontiac","model_name":"Firebird","product_year":1969},
    {"car_name":"Nissan","model_name":"Datsun/Nissan Z-car","product_year":1990},
    {"car_name":"Ford","model_name":"Focus","product_year":2013},
    {"car_name":"Ford","model_name":"Crown Victoria","product_year":2010},
    {"car_name":"Porsche","model_name":"911","product_year":1992},
    {"car_name":"BMW","model_name":"M3","product_year":1997},
    {"car_name":"Ford","model_name":"Econoline E350","product_year":1999},
    {"car_name":"Acura","model_name":"TL","product_year":2001},
    {"car_name":"Oldsmobile","model_name":"Aurora","product_year":1999},
    {"car_name":"Mitsubishi","model_name":"Montero Sport","product_year":2004},
    {"car_name":"Bentley","model_name":"Azure","product_year":2008},
    {"car_name":"Nissan","model_name":"Pathfinder","product_year":1999},
    {"car_name":"GMC","model_name":"Yukon XL 2500","product_year":2002},
    {"car_name":"Chevrolet","model_name":"Corvette","product_year":2005},
    {"car_name":"Chevrolet","model_name":"Camaro","product_year":1999},
    {"car_name":"Porsche","model_name":"968","product_year":1992},
    {"car_name":"Dodge","model_name":"Dakota","product_year":2001},
    {"car_name":"Jeep","model_name":"Patriot","product_year":2008},
    {"car_name":"Cadillac","model_name":"DeVille","product_year":2005},
    {"car_name":"Chevrolet","model_name":"S10","product_year":1992},
    {"car_name":"Mazda","model_name":"B-Series Plus","product_year":2004},
    {"car_name":"Chevrolet","model_name":"Monte Carlo","product_year":2001},
    {"car_name":"Mercedes-Benz","model_name":"CL-Class","product_year":2011},
    {"car_name":"Chevrolet","model_name":"Cobalt","product_year":2010},
    {"car_name":"Oldsmobile","model_name":"98","product_year":1993},
    {"car_name":"Aston Martin","model_name":"DB9","product_year":2012},
    {"car_name":"Mercury","model_name":"Milan","product_year":2006},
    {"car_name":"Ford","model_name":"Ranger","product_year":1993},
    {"car_name":"Volvo","model_name":"XC70","product_year":2008},
    {"car_name":"Dodge","model_name":"Neon","product_year":1996},
    {"car_name":"Chevrolet","model_name":"S10 Blazer","product_year":1994},
    {"car_name":"Toyota","model_name":"Camry","product_year":2006},
    {"car_name":"Ram","model_name":"1500","product_year":2012},
    {"car_name":"Mitsubishi","model_name":"Lancer Evolution","product_year":2005},
    {"car_name":"Chevrolet","model_name":"Equinox","product_year":2005},
    {"car_name":"Hummer","model_name":"H1","product_year":1993},
    {"car_name":"Ford","model_name":"Edge","product_year":2010},
    {"car_name":"Dodge","model_name":"Dakota Club","product_year":1992},
    {"car_name":"Ford","model_name":"Tempo","product_year":1986},
    {"car_name":"Chevrolet","model_name":"S10","product_year":1999},
    {"car_name":"Toyota","model_name":"Paseo","product_year":1996},
    {"car_name":"Isuzu","model_name":"Trooper","product_year":1994},
    {"car_name":"Lincoln","model_name":"Navigator L","product_year":2011},
    {"car_name":"Honda","model_name":"CR-Z","product_year":2011},
    {"car_name":"BMW","model_name":"X3","product_year":2011},
    {"car_name":"Mitsubishi","model_name":"Montero Sport","product_year":2004},
    {"car_name":"Toyota","model_name":"RAV4","product_year":2009},
    {"car_name":"Toyota","model_name":"Venza","product_year":2012},
    {"car_name":"Dodge","model_name":"Viper RT/10","product_year":1993},
    {"car_name":"Ford","model_name":"Ranger","product_year":1994},
    {"car_name":"Mazda","model_name":"626","product_year":1989},
    {"car_name":"MINI","model_name":"MINI","product_year":2002},
    {"car_name":"Dodge","model_name":"D150","product_year":1992},
    {"car_name":"Cadillac","model_name":"STS","product_year":2005},
    {"car_name":"Mercedes-Benz","model_name":"E-Class","product_year":1998},
    {"car_name":"GMC","model_name":"Safari","product_year":1999},
    {"car_name":"Dodge","model_name":"Stratus","product_year":1997},
    {"car_name":"Ford","model_name":"Festiva","product_year":1988},
    {"car_name":"Chevrolet","model_name":"Silverado 3500","product_year":2006},
    {"car_name":"Ford","model_name":"Econoline E150","product_year":1997},
    {"car_name":"Nissan","model_name":"Frontier","product_year":2008},
    {"car_name":"Nissan","model_name":"Quest","product_year":1996},
    {"car_name":"Suzuki","model_name":"Vitara","product_year":2003},
    {"car_name":"BMW","model_name":"Z4","product_year":2008},
    {"car_name":"Mazda","model_name":"MPV","product_year":2001},
    {"car_name":"Buick","model_name":"Coachbuilder","product_year":1991},
    {"car_name":"Subaru","model_name":"Legacy","product_year":1998},
    {"car_name":"Holden","model_name":"VS Commodore","product_year":1997},
    {"car_name":"Mazda","model_name":"929","product_year":1988},
    {"car_name":"Toyota","model_name":"Corolla","product_year":2003},
    {"car_name":"Isuzu","model_name":"VehiCROSS","product_year":2000},
    {"car_name":"Volvo","model_name":"940","product_year":1993},
    {"car_name":"Lexus","model_name":"LX","product_year":2006},
    {"car_name":"Infiniti","model_name":"QX","product_year":2001}];

//All car brand's

let allCarBtn = document.querySelector(`#allcar-btn`);
allCarBtn.addEventListener(`click`,function () {
    displayAllCars(carData);
});

//Search Logic

let searchBox = document.querySelector(`#car-search`);
searchBox.addEventListener(`keyup`,function () {
    let textEntered = searchBox.value;
    console.log(textEntered);
    if(textEntered !== ''){
        let filteredCars = carData.filter(function (automobile) {
            return automobile.car_name.toUpperCase().startsWith(textEntered.toUpperCase());
        });
        displayAllCars(filteredCars);
    }else {
        displayAllCars([]);
    }
});

//displayAllCars
let displayAllCars = (carData) => {
     document.querySelector(`#found-count`).innerText = carData.length ;
     let tableBody = document.querySelector(`#table-body`);
     let output = '';
     for(let automobile of carData){
         output += `<tr>
                        <td>${automobile.car_name}</td>
                        <td>${automobile.model_name}</td>
                        <td>${automobile.product_year}</td>
                     </tr>\n`;
     }
     tableBody.innerHTML = output;
};
